config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only =>[:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup', :to => "users#new"
  match "/signin", :to => "sessions#new"
  match '/contact', :to => "pages#contact"

  match '/about', :to => "pages#about"
  match '/help', :to => "pages#help"
  match "/signout", :to => "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => "pages#home"

end

app/views/shared/_error_messages.html.erb
<%if object.errors.any? %>
    <div id="error_explanation" class="round">
	<h2><%= pluralize(object.errors.count, "error") %>
	prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved</h2>
	<p>Please fix problems with the following fields:</p>
	<ul>
	<% object.errors.full_messages.each do |err| %>
	    <li><%= err %></li>
	<% end %>
	</ul>
    </div>
<% end %>

	    

app/views/shared/_feed_items.html.erb
<% unless @feed_items.blank? %>

    <%= will_paginate @feed_items %>

    <table>
      <%= render :partial => "shared/feed_single_item", :collection =>@feed_items, :as => :micropost %>
    </table>
<% end %>

app/views/shared/_feed_single_item.html.erb
<%= render :partial =>"microposts/micropost", :object => micropost, :as =>:micropost,
     :locals => {:multi_user_feed => true }%>

app/views/shared/_flash.html.erb
<% option ||= {}
   controller.flash.each do |tag, value|
       if option[:table] %>
        <tr>
          <td>
        <% end %>
        <%=content_tag(:div, value, :class=>"flash #{tag}") %>
        <% if option[:table] %>
            </td></tr>
        <% end %>
    <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost  do |m|   %>
<%= render 'shared/error_messages', :object => @current_user %>
    <div class="field">
    <%= m.text_area :content %>
    </div>
    <%= m.submit "Post" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
        <span id="following" class="stat">
            <%= @user.following.count %> following
        </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
        <span id="followers" class="stat">
        <%= pluralize(@user.followers.count, "follower") %>
        </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
        <%= current_user.name %>
    </span>
    <span class="microposts">
        <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
  <%= render :partial => "shared/stats" %>
</div>